import * as T from 'three';
export type CarState={x:number;z:number;yaw:number;speed:number;steer:number;slip:number;score:number;lap:number;progress:number;gear:number;time:number;done:boolean};
export const fresh=():CarState=>({x:0,z:180,yaw:Math.PI/2,speed:0,steer:0,slip:0,score:0,lap:0,progress:0,gear:1,time:0,done:false});
export const track=(a:number)=>new T.Vector3(Math.sin(a)*260,0,Math.cos(a)*180);
export function step(s:CarState,keys:Set<string>,dt:number,mode:string){if(s.done)return;s.time+=dt;const throttle=keys.has('w')||keys.has('ArrowUp');const brake=keys.has('s')||keys.has('ArrowDown');const hand=keys.has(' ');const steering=Number(keys.has('a')||keys.has('ArrowLeft'))-Number(keys.has('d')||keys.has('ArrowRight'));s.steer+=(steering-s.steer)*Math.min(1,dt*7);s.speed+=((throttle?20:0)-(brake?40:0)-s.speed*.16-(hand?8:0))*dt;s.speed=Math.max(0,Math.min(78,s.speed));const grip=hand?.7:mode==='drift'?2.3:5;s.slip+=(s.steer*s.speed*.011*(hand?2.5:1)-s.slip)*Math.min(1,dt*grip);s.yaw+=s.steer*s.speed*.008*dt;s.x+=Math.sin(s.yaw-s.slip)*s.speed*dt;s.z+=Math.cos(s.yaw-s.slip)*s.speed*dt;const a=(Math.atan2(s.x/260,s.z/180)+Math.PI*2)%(Math.PI*2);const center=track(a);const distance=Math.hypot(s.x-center.x,s.z-center.z);if(distance>19){s.speed*=Math.pow(.97,dt*60);if(distance>28){const f=28/distance;s.x=center.x+(s.x-center.x)*f;s.z=center.z+(s.z-center.z)*f;s.slip*=.5;}}let delta=a-s.progress;if(delta<-Math.PI)delta+=Math.PI*2;if(delta>Math.PI)delta-=Math.PI*2;if(delta>0&&delta<.15){if(s.progress>6&&a<.3)s.lap++;}s.progress=a;if(Math.abs(s.slip)>.16&&s.speed>12&&distance<19)s.score+=Math.abs(s.slip)*s.speed*dt*10;s.gear=Math.max(1,Math.min(6,Math.floor(s.speed/13)+1));if(mode==='drift'&&s.time>=90||mode==='race'&&s.lap>=3)s.done=true;}
export function createWorld(host:HTMLElement){const scene=new T.Scene();scene.background=new T.Color('#131b2e');scene.fog=new T.Fog('#131b2e',180,850);const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;host.appendChild(renderer.domElement);const camera=new T.PerspectiveCamera(75,1,.1,1500);scene.add(new T.HemisphereLight(0xa7c6ff,0x303025,2));const light=new T.DirectionalLight(0xffc895,2.5);light.position.set(-200,180,100);scene.add(light);
const mat=(c:string)=>new T.MeshStandardMaterial({color:c,roughness:.7});const asphalt=mat('#353b46'),groundMat=mat('#192c28');const ground=new T.Mesh(new T.PlaneGeometry(2400,2400),groundMat);ground.rotation.x=-Math.PI/2;ground.position.y=-.1;scene.add(ground);
function box(w:number,h:number,d:number,x:number,y:number,z:number,m:T.Material){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);scene.add(mesh);return mesh;}
const pts:number[]=[];for(let i=0;i<=360;i++){let a=i/360*Math.PI*2;const p=track(a);const normal=new T.Vector3(Math.sin(a)/260,0,Math.cos(a)/180).normalize();for(const side of [-1,1])pts.push(p.x+normal.x*side*20,.01,p.z+normal.z*side*20);}const indices:number[]=[];for(let i=0;i<360;i++){let n=i*2;indices.push(n,n+1,n+2,n+1,n+3,n+2);}const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(pts,3));geom.setIndex(indices);geom.computeVertexNormals();const road=new T.Mesh(geom,asphalt);road.material.side=T.DoubleSide;scene.add(road);
for(let i=0;i<180;i++){const a=i/180*Math.PI*2,p=track(a),next=track(a+.01),angle=Math.atan2(next.x-p.x,next.z-p.z);if(i%2===0){const m=box(.25,.03,3.8,p.x,.04,p.z,mat('#b3ada1'));m.rotation.y=angle;}for(const side of [-1,1]){const n=new T.Vector3(Math.sin(a)/260,0,Math.cos(a)/180).normalize();const curb=box(1.1,.15,7,p.x+n.x*side*20,.08,p.z+n.z*side*20,mat(i%2?'#ede8d8':'#e64b36'));curb.rotation.y=angle;const wall=box(.7,1.1,7.6,p.x+n.x*side*23,.55,p.z+n.z*side*23,mat('#687380'));wall.rotation.y=angle;}if(i%8===0){const n=new T.Vector3(Math.sin(a),0,Math.cos(a));const x=p.x+n.x*29,z=p.z+n.z*29;box(.3,10,.3,x,5,z,mat('#414c5b'));const lamp=box(2,.2,1,x,10,z,new T.MeshBasicMaterial({color:0xffd6a3}));lamp.rotation.y=angle;}}
for(let i=0;i<90;i++){const a=i/90*Math.PI*2;const radius=400+(i%5)*24;const h=16+(i*37%90);box(16+(i%3)*9,h,19,Math.sin(a)*radius,h/2,Math.cos(a)*radius,mat(i%2?'#273548':'#303e52'));}for(let i=0;i<20;i++){box(8,.04,1.5,(i%2)*8-4,.06,180+(Math.floor(i/2)-5)*1.5,mat(i%2?'#eeeeee':'#111111'));}
const rivals=new Map<string,T.Group>();function car(id:string){if(rivals.has(id))return rivals.get(id)!;const group=new T.Group();const body=new T.Mesh(new T.BoxGeometry(1.9,.65,4),mat('#ff583c'));body.position.y=.65;const cab=new T.Mesh(new T.BoxGeometry(1.6,.6,1.9),mat('#1b2533'));cab.position.set(0,1.2,-.15);group.add(body,cab);for(const x of [-.7,.7]){const tail=new T.Mesh(new T.BoxGeometry(.5,.14,.1),new T.MeshBasicMaterial({color:0xff2211}));tail.position.set(x,.7,-2.05);group.add(tail);}scene.add(group);rivals.set(id,group);return group;}
const resize=()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();return {render(s:CarState,others:{token:string;x:number;z:number;yaw:number}[],bots:boolean){camera.position.set(s.x,1.45+Math.sin(s.time*20)*s.speed*.0005,s.z);const direction=new T.Vector3(Math.sin(s.yaw+s.slip*.15),-.045,Math.cos(s.yaw+s.slip*.15));camera.lookAt(camera.position.clone().add(direction));camera.rotation.z=-s.steer*s.speed*.0009;const visible=new Set<string>();for(const o of others){visible.add(o.token);const c=car(o.token);c.visible=true;c.position.lerp(new T.Vector3(o.x,0,o.z),.3);c.rotation.y=o.yaw;}if(bots)for(let i=0;i<3;i++){const id='bot'+i;visible.add(id);const a=(s.time*(.033+i*.002)+.12+i*.08)%(Math.PI*2);const p=track(a),next=track(a+.01),c=car(id);c.visible=true;c.position.copy(p);c.rotation.y=Math.atan2(next.x-p.x,next.z-p.z);}for(const [id,c]of rivals)c.visible=visible.has(id);renderer.render(scene,camera);},dispose(){observer.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)m.dispose();}});renderer.dispose();host.replaceChildren();}};}
